version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/frontend
    steps:
      - checkout:
          path: ~/frontend
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run: $(yarn bin)/cypress run --record --key <record_key>
      - add_ssh_keys:
          fingerprints:
            - "32:04:f0:a0:7e:7f:94:f5:72:1a:38:68:7c:f3:f9:a7"
#      - run:
#          name: Deploy docs to gh-pages branch
#          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'
