version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          record: true        # record results on Cypress Dashboard
          parallel: true      # split all specs across machines
          parallelism: 4      # use 4 CircleCI machines to finish quickly
          group: 'all tests'  # name this group "all tests" on the dashboard
          start: 'npm start'  # start server before running tests
#          run: $(yarn bin)/cypress run --record --key 49100f76-2f4e-4870-a587-72411073c821
#
#          - add_ssh_keys:
#              fingerprints:
#                - "32:04:f0:a0:7e:7f:94:f5:72:1a:38:68:7c:f3:f9:a7"
